### ISSUE TITLE
Mettere path assoluta nell'usare JavaFx

### ISSUE THREAD

**Issue by matteotoma98** [Gasu16/Bpmn#1]
java --module-path /home/matt/OpenJFX/javafx-sdk-17.0.0.1/lib --add-modules=javafx.controls,javafx.fxml -jar target/Translator-1.0-SNAPSHOT-jar-with-dependencies.jar

Non va bene, dobbiamo mettere javafx lib magari dentro questa cartella

**Comment by matteotoma98** [comment]
O come soluzione ottimale, dal dockerfile installare javafx (poi settare bene la workingdir)

**Comment by zer0matt** [comment]
Ovviamente la path va cambiata, quella è la path mia e vale solo per me
