### ISSUE TITLE
Execute message carica anche i messaggi che non esistono

### ISSUE THREAD

**Issue by zer0matt** [Gasu16/Bpmn#2]
### Breve descrizione del problema
Quando si va a premere il bottone "execute message", il campo "MessageID" è irrilevante, qualunque cosa scrivi lo accetterà comunque.

### Fix proposto
Suggerisco di mettere un controllo sul campo che verifichi se il MessaggeID inserito è effettivamente presente nella lista dei messaggi recuperata tramite GetMessageList.

Assegno la issue a tutti, così il primo che implementa il fix può aprire una nuova PR.

**Comment by Gasu16** [comment]
Risolto con il commit #ddaccef

**Comment by Gasu16** [comment]
Fixed with commit ddaccef659ff2bac0321d0ba553142ccfca6ec0d

**Comment by zer0matt** [comment]
Fixed with commit ddaccef659ff2bac0321d0ba553142ccfca6ec0d
